-- MySQL Script generated by MySQL Workbench
-- Wed Dec 10 01:40:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sgcm_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgcm_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgcm_bd` ;
USE `sgcm_bd` ;

-- -----------------------------------------------------
-- Table `sgcm_bd`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_bd`.`tipo_usuario` (
  `id` INT NOT NULL auto_increment,
  `nome` VARCHAR(45) NULL,
  `modulo_administrativo` VARCHAR(1) NOT NULL,
  `modulo_estacionamento` VARCHAR(1) NOT NULL,
  `modulo_atendimento` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_bd`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_bd`.`usuarios` (
  `id` INT NOT NULL auto_increment,
  `nome` VARCHAR(50) NULL,
  `nascimento` DATE NULL,
  `cpf` VARCHAR(15) NULL,
  `senha` VARCHAR(128) NOT NULL,
  `endereco` VARCHAR(250) NULL,
  `tipo_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_tipo_usuario_idx` (`tipo_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `sgcm_bd`.`tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_bd`.`carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_bd`.`carro` (
  `id` INT NOT NULL auto_increment,
  `placa` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `cor` VARCHAR(45) NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carro_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_carro_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `sgcm_bd`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_bd`.`vaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_bd`.`vaga` (
  `id` INT NOT NULL auto_increment,
  `numero_vaga` INT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_bd`.`estacionamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_bd`.`estacionamento` (
  `id` INT NOT NULL auto_increment,
  `entrada_datetime` DATETIME NULL,
  `saida_datetime` DATETIME NULL,
  `valor_total` DOUBLE NULL,
  `usuarios_id` INT NOT NULL,
  `vaga_id` INT NOT NULL,
  `carro_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estacionamento_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_estacionamento_vaga1_idx` (`vaga_id` ASC) VISIBLE,
  INDEX `fk_estacionamento_carro1_idx` (`carro_id` ASC) VISIBLE,
  CONSTRAINT `fk_estacionamento_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `sgcm_bd`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estacionamento_vaga1`
    FOREIGN KEY (`vaga_id`)
    REFERENCES `sgcm_bd`.`vaga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estacionamento_carro1`
    FOREIGN KEY (`carro_id`)
    REFERENCES `sgcm_bd`.`carro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `sgcm_bd`.`tipo_usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgcm_bd`;
INSERT INTO `sgcm_bd`.`tipo_usuario` (`id`, `nome`, `modulo_administrativo`, `modulo_estacionamento`, `modulo_atendimento`) VALUES (1024, 'admin', 'S', 'S', 'S');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgcm_bd`.`usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgcm_bd`;
INSERT INTO `sgcm_bd`.`usuarios` (`id`, `nome`, `nascimento`, `cpf`, `senha`, `endereco`, `tipo_usuario_id`) VALUES (1024, 'admin', null , '', 'cbfb296f4c8a4035741cf74cadc294b8cb2b66dc21497443d6267897ce9e10cb1b27d62667e2cf92be9ca7bac9c483130b7d896361d4c09dfa6202b20b5463c8', '', 1024);

COMMIT;

